# Generated by Django 6.0.5 on 2026-05-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaseTratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ordem_cronologica', models.IntegerField()),
                ('status', models.CharField(choices=[('concluida', 'Concluída'), ('atual', 'Atual'), ('pendente', 'Pendente')], default='pendente', max_length=20)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['ordem_cronologica'],
            },
        ),
    ]
