# Generated by Django 6.0.5 on 2026-05-21 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamento', '0003_convitecopiloto_vinculocopiloto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convitecopiloto',
            name='email_parceiro',
        ),
        migrations.RemoveField(
            model_name='convitecopiloto',
            name='nome_parceiro',
        ),
        migrations.RemoveField(
            model_name='convitecopiloto',
            name='telefone_parceiro',
        ),
        migrations.AddField(
            model_name='convitecopiloto',
            name='nome_identificador',
            field=models.CharField(default='Sem Nome', help_text='Ex: Marido, Minha Mãe', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='convitecopiloto',
            name='perm_receber_lembretes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='convitecopiloto',
            name='perm_ver_agenda',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='convitecopiloto',
            name='perm_ver_fase',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='convitecopiloto',
            name='perm_ver_medicacoes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vinculocopiloto',
            name='convite_origem',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tratamento.convitecopiloto'),
        ),
        migrations.AlterField(
            model_name='convitecopiloto',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aceito', 'Aceito'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
    ]
