/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as RecuperarCodigoRouteImport } from './routes/recuperar-codigo'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConviteTokenRouteImport } from './routes/convite.$token'
import { Route as AppVideotecaRouteImport } from './routes/_app.videoteca'
import { Route as AppTimelineRouteImport } from './routes/_app.timeline'
import { Route as AppPerfilRouteImport } from './routes/_app.perfil'
import { Route as AppNotificacoesRouteImport } from './routes/_app.notificacoes'
import { Route as AppNotasRouteImport } from './routes/_app.notas'
import { Route as AppMedicacoesRouteImport } from './routes/_app.medicacoes'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppHelpRouteImport } from './routes/_app.help'
import { Route as AppExamesRouteImport } from './routes/_app.exames'
import { Route as AppCopilotoRouteImport } from './routes/_app.copiloto'
import { Route as AppContatosRouteImport } from './routes/_app.contatos'
import { Route as AppComoEstouHojeRouteImport } from './routes/_app.como-estou-hoje'
import { Route as AppCalendarioRouteImport } from './routes/_app.calendario'

const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarCodigoRoute = RecuperarCodigoRouteImport.update({
  id: '/recuperar-codigo',
  path: '/recuperar-codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteTokenRoute = ConviteTokenRouteImport.update({
  id: '/convite/$token',
  path: '/convite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVideotecaRoute = AppVideotecaRouteImport.update({
  id: '/videoteca',
  path: '/videoteca',
  getParentRoute: () => AppRoute,
} as any)
const AppTimelineRoute = AppTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificacoesRoute = AppNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppNotasRoute = AppNotasRouteImport.update({
  id: '/notas',
  path: '/notas',
  getParentRoute: () => AppRoute,
} as any)
const AppMedicacoesRoute = AppMedicacoesRouteImport.update({
  id: '/medicacoes',
  path: '/medicacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppExamesRoute = AppExamesRouteImport.update({
  id: '/exames',
  path: '/exames',
  getParentRoute: () => AppRoute,
} as any)
const AppCopilotoRoute = AppCopilotoRouteImport.update({
  id: '/copiloto',
  path: '/copiloto',
  getParentRoute: () => AppRoute,
} as any)
const AppContatosRoute = AppContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => AppRoute,
} as any)
const AppComoEstouHojeRoute = AppComoEstouHojeRouteImport.update({
  id: '/como-estou-hoje',
  path: '/como-estou-hoje',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarioRoute = AppCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recuperar-codigo': typeof RecuperarCodigoRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/calendario': typeof AppCalendarioRoute
  '/como-estou-hoje': typeof AppComoEstouHojeRoute
  '/contatos': typeof AppContatosRoute
  '/copiloto': typeof AppCopilotoRoute
  '/exames': typeof AppExamesRoute
  '/help': typeof AppHelpRoute
  '/home': typeof AppHomeRoute
  '/medicacoes': typeof AppMedicacoesRoute
  '/notas': typeof AppNotasRoute
  '/notificacoes': typeof AppNotificacoesRoute
  '/perfil': typeof AppPerfilRoute
  '/timeline': typeof AppTimelineRoute
  '/videoteca': typeof AppVideotecaRoute
  '/convite/$token': typeof ConviteTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recuperar-codigo': typeof RecuperarCodigoRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/calendario': typeof AppCalendarioRoute
  '/como-estou-hoje': typeof AppComoEstouHojeRoute
  '/contatos': typeof AppContatosRoute
  '/copiloto': typeof AppCopilotoRoute
  '/exames': typeof AppExamesRoute
  '/help': typeof AppHelpRoute
  '/home': typeof AppHomeRoute
  '/medicacoes': typeof AppMedicacoesRoute
  '/notas': typeof AppNotasRoute
  '/notificacoes': typeof AppNotificacoesRoute
  '/perfil': typeof AppPerfilRoute
  '/timeline': typeof AppTimelineRoute
  '/videoteca': typeof AppVideotecaRoute
  '/convite/$token': typeof ConviteTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/recuperar-codigo': typeof RecuperarCodigoRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/_app/calendario': typeof AppCalendarioRoute
  '/_app/como-estou-hoje': typeof AppComoEstouHojeRoute
  '/_app/contatos': typeof AppContatosRoute
  '/_app/copiloto': typeof AppCopilotoRoute
  '/_app/exames': typeof AppExamesRoute
  '/_app/help': typeof AppHelpRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/medicacoes': typeof AppMedicacoesRoute
  '/_app/notas': typeof AppNotasRoute
  '/_app/notificacoes': typeof AppNotificacoesRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/timeline': typeof AppTimelineRoute
  '/_app/videoteca': typeof AppVideotecaRoute
  '/convite/$token': typeof ConviteTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recuperar-codigo'
    | '/recuperar-senha'
    | '/calendario'
    | '/como-estou-hoje'
    | '/contatos'
    | '/copiloto'
    | '/exames'
    | '/help'
    | '/home'
    | '/medicacoes'
    | '/notas'
    | '/notificacoes'
    | '/perfil'
    | '/timeline'
    | '/videoteca'
    | '/convite/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/recuperar-codigo'
    | '/recuperar-senha'
    | '/calendario'
    | '/como-estou-hoje'
    | '/contatos'
    | '/copiloto'
    | '/exames'
    | '/help'
    | '/home'
    | '/medicacoes'
    | '/notas'
    | '/notificacoes'
    | '/perfil'
    | '/timeline'
    | '/videoteca'
    | '/convite/$token'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/recuperar-codigo'
    | '/recuperar-senha'
    | '/_app/calendario'
    | '/_app/como-estou-hoje'
    | '/_app/contatos'
    | '/_app/copiloto'
    | '/_app/exames'
    | '/_app/help'
    | '/_app/home'
    | '/_app/medicacoes'
    | '/_app/notas'
    | '/_app/notificacoes'
    | '/_app/perfil'
    | '/_app/timeline'
    | '/_app/videoteca'
    | '/convite/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecuperarCodigoRoute: typeof RecuperarCodigoRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  ConviteTokenRoute: typeof ConviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-codigo': {
      id: '/recuperar-codigo'
      path: '/recuperar-codigo'
      fullPath: '/recuperar-codigo'
      preLoaderRoute: typeof RecuperarCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite/$token': {
      id: '/convite/$token'
      path: '/convite/$token'
      fullPath: '/convite/$token'
      preLoaderRoute: typeof ConviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/videoteca': {
      id: '/_app/videoteca'
      path: '/videoteca'
      fullPath: '/videoteca'
      preLoaderRoute: typeof AppVideotecaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/timeline': {
      id: '/_app/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof AppTimelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notificacoes': {
      id: '/_app/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AppNotificacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notas': {
      id: '/_app/notas'
      path: '/notas'
      fullPath: '/notas'
      preLoaderRoute: typeof AppNotasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/medicacoes': {
      id: '/_app/medicacoes'
      path: '/medicacoes'
      fullPath: '/medicacoes'
      preLoaderRoute: typeof AppMedicacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/help': {
      id: '/_app/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exames': {
      id: '/_app/exames'
      path: '/exames'
      fullPath: '/exames'
      preLoaderRoute: typeof AppExamesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/copiloto': {
      id: '/_app/copiloto'
      path: '/copiloto'
      fullPath: '/copiloto'
      preLoaderRoute: typeof AppCopilotoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contatos': {
      id: '/_app/contatos'
      path: '/contatos'
      fullPath: '/contatos'
      preLoaderRoute: typeof AppContatosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/como-estou-hoje': {
      id: '/_app/como-estou-hoje'
      path: '/como-estou-hoje'
      fullPath: '/como-estou-hoje'
      preLoaderRoute: typeof AppComoEstouHojeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendario': {
      id: '/_app/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AppCalendarioRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCalendarioRoute: typeof AppCalendarioRoute
  AppComoEstouHojeRoute: typeof AppComoEstouHojeRoute
  AppContatosRoute: typeof AppContatosRoute
  AppCopilotoRoute: typeof AppCopilotoRoute
  AppExamesRoute: typeof AppExamesRoute
  AppHelpRoute: typeof AppHelpRoute
  AppHomeRoute: typeof AppHomeRoute
  AppMedicacoesRoute: typeof AppMedicacoesRoute
  AppNotasRoute: typeof AppNotasRoute
  AppNotificacoesRoute: typeof AppNotificacoesRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppTimelineRoute: typeof AppTimelineRoute
  AppVideotecaRoute: typeof AppVideotecaRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarioRoute: AppCalendarioRoute,
  AppComoEstouHojeRoute: AppComoEstouHojeRoute,
  AppContatosRoute: AppContatosRoute,
  AppCopilotoRoute: AppCopilotoRoute,
  AppExamesRoute: AppExamesRoute,
  AppHelpRoute: AppHelpRoute,
  AppHomeRoute: AppHomeRoute,
  AppMedicacoesRoute: AppMedicacoesRoute,
  AppNotasRoute: AppNotasRoute,
  AppNotificacoesRoute: AppNotificacoesRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppTimelineRoute: AppTimelineRoute,
  AppVideotecaRoute: AppVideotecaRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RecuperarCodigoRoute: RecuperarCodigoRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  ConviteTokenRoute: ConviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
